version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: users_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: usersdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"   # opcional, útil para conectarte desde host
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  app:
    build: .
    container_name: users_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASS: userpassword
      DB_NAME: usersdb
      PORT: 8080
    restart: unless-stopped

volumes:
  db_data:
